services:
  postgres:
    image: postgres:15
    container_name: postgres  # bukan "postgress"
    restart: unless-stopped
    environment:
      POSTGRES_DB: vazzuniverse_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vazzuniverse_local"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s